custom_paths=(
    "$HOME/.local/bin"
    "$HOME/bin"
    "/usr/local/opt/mysql-client/bin"
    "/usr/local/opt/libpq/bin"
    "/Applications/Sublime Text.app/Contents/SharedSupport/bin"
    "/Applications/Sublime Merge.app/Contents/SharedSupport/bin"
)
export PATH="${(j.:.)custom_paths}:$PATH"
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=(
    rust
    stack
)
source $ZSH/oh-my-zsh.sh

# export NVM_DIR="$HOME/.nvm" # nvm
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(pyenv init --path)" # pyenv
eval "$(rbenv init -)" # rbenv
source $HOME/.cargo/env # Rust

# alias swift-init='swift package init --type=executable' # for swift
